// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "MainPage": {
    "welcome_message": "Welcome!",
    "about_app": "REST Client is a lightweight API testing tool designed to simplify working with RESTful services. Whether you are debugging an API, testing endpoints, or managing request history, REST Client provides an intuitive and efficient experience. With built-in authentication, request history tracking, and support for various HTTP methods, you can seamlessly interact with any API. Start exploring now—sign in to begin your API journey!"
  }
};
export default messages;